name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
    - name: Get commit data
      uses: rlespinasse/git-commit-data-action@v1.x
    - run: git config --global user.email "${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
    - run: git config --global user.name "${{ env.GIT_COMMIT_AUTHOR_NAME }}"
    - run: npm ci
    - run: npm run deploy
      